### ISSUE TITLE
Why does -n go up and output go up ?

### ISSUE THREAD

**Issue by lanjingling0510** [pod4g/hiper#19]
Isn't the output average ?

![wx20180608-102049](https://user-images.githubusercontent.com/11639669/41135758-a964bd52-6b05-11e8-8ed4-803bae867c0b.png)
![wx20180608-102056](https://user-images.githubusercontent.com/11639669/41135761-ada33e66-6b05-11e8-9bb5-d534881f99b5.png)

**Comment by pod4g** [comment]
I'll check the questions and thank you for your feedback

**Comment by pod4g** [comment]
fix. please upgrade your version to `0.0.16`
