### ISSUE TITLE
No file or directory

### ISSUE THREAD

**Issue by silenceboychen** [pod4g/hiper#20]
![image](https://user-images.githubusercontent.com/15072399/41137417-9ea4ecd6-6b0d-11e8-869f-19343c93a159.png)
why?

**Comment by pod4g** [comment]
Hi, see #5

**Comment by pod4g** [comment]
The problem has been solved, please upgrade hiper to `0.0.15`

run below to upgrade:

```bash
npm i hiper -g
``` 

thr pr: https://github.com/pod4g/hiper/pull/21
