### ISSUE TITLE
New Design for Hiper

### ISSUE THREAD

**Issue by Yasujizr** [pod4g/hiper#4]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a icon.

Best Regards.

**Comment by pod4g** [comment]
Hi, This is an urgent matter for me now. The critical moment, you are here. I really appreciate you，I want a letter of logo（like vue's logo）

like this (but i just want the letter `h`)，what do you think ?

![logo](https://user-images.githubusercontent.com/12889190/40983004-34638664-6911-11e8-8425-3c14eeec6193.png)

**Comment by pod4g** [comment]
Your idea and example are excellent. thank you very very much

**Comment by Yasujizr** [comment]
I can send a PR if you want, or we can develop the icon according to your wishes.

**Comment by pod4g** [comment]
OK. here we go

**Comment by Yasujizr** [comment]
I send PR? Or you want the icon to change? Colors is right for you? You want add anything on logo?

**Comment by pod4g** [comment]
![](https://user-images.githubusercontent.com/36993664/41000635-4a5ca79c-6917-11e8-93de-0b9c646f7449.png)
This logo is ok

**Comment by Yasujizr** [comment]
All File; https://drive.google.com/drive/u/4/folders/1WyPbitdKiVO5Y1xsjN2IexrMDbbCF2W-

**Comment by Pablodotnet** [comment]
@Yasujizr I remembered you were in this repository, now I'm making a little open source tool, if you are still designing open source projects' logos I would be glad to have some of your work done to my project
